cloud:
  aws:
    s3:
      bucket: ENC(Y9/m8FGlrTWFDRn9zth7Ye3JycfihVDMKlhMgAMR5es=)
    region:
      static: ap-northeast-2
    stack:
      auto: false
    credentials:
      access-key: ENC(f/BFp0lc1SBw4Y6Dtd9NpQ8Ot14rW324W5kGCfF7EyI=)
      secret-key: ENC(SBAHhq7tWmzSwmLH+ZkSs14R8bggsVbMy1CpcF5rW1cvi/8iiSk2n7n7qeZpQp9oFGEJOV54xR0=)

logging:
  level:
    com:
      amazonaws:
        util:
          EC2MetadataUtils: error
spring:
  servlet:
    multipart:
      max-file-size: 100MB
      max-request-size: 100MB