spring:
  datasource:
    driver-class-name: com.mysql.cj.jdbc.Driver
  jpa:
    hibernate:
      ddl-auto: update
    properties:
      hibernate:
        diarect: org.hibernate.dialect.
        show_sql: true
        format_sql: true
    database: mysql

  redis:
    host: localhost
    port: 6379

logging:
  level:
    org.hibernate: info

--- # dev

spring:
  config:
    activate:
      on-profile: db-dev
  datasource:
    url: jdbc:mysql://localhost:3306/aejimeongji
    username: ENC(Y6L0QOZTlGyb1pOzghKt1w==)
    password: ENC(fxt0Prk+0UFxLrhIX9YzXQ==)
    driver-class-name: com.mysql.cj.jdbc.Driver

logging:
  level:
    org.hibernate:
      type.descriptor: trace

--- # prod

spring:
  config:
    activate:
      on-profile: db-prod
  datasource:
    url: jdbc:mysql://localhost:3306/aejimeongji
    username: ENC(bRdQh0yTV/2bjCLiyjtqQw==)
    password: ENC(ChrtKWCvlRCddol33RoIJQ==)
    driver-class-name: com.mysql.cj.jdbc.Driver

--- # test

spring:
  config:
    activate:
      on-profile: db-test
  datasource:
    url: jdbc:h2:mem:test
    username: sa
    driver-class-name: org.h2.Driver
  jpa:
    database: h2

logging:
  level:
    org.hibernate:
      type.descriptor: trace